export const FILE_TEMPLATES: Record<string, string> = {
  html: '<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>Document</title>\n</head>\n<body>\n  \n</body>\n</html>',
  htm: '<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>Document</title>\n</head>\n<body>\n  \n</body>\n</html>',
  js: '// JavaScript code\n',
  ts: '// TypeScript code\n',
  jsx: 'import React from "react";\n\nfunction Component() {\n  return <div></div>;\n}\n\nexport default Component;\n',
  tsx: 'import React from "react";\n\ninterface Props {}\n\nfunction Component({}: Props) {\n  return <div></div>;\n}\n\nexport default Component;\n',
  css: '/* CSS */\n',
  scss: '// SCSS\n',
  less: '// Less\n',
  php: '<?php\n// PHP code\n',
  json: '{\n  \n}',
  md: '# Title\n\nContent here\n',
  py: '# Python code\n',
  rb: '# Ruby code\n',
  go: 'package main\n\nfunc main() {\n  \n}\n',
  rs: 'fn main() {\n  println!("Hello, world!");\n}\n',
  java: 'public class Main {\n  public static void main(String[] args) {\n    \n  }\n}\n',
  c: '#include <stdio.h>\n\nint main() {\n  return 0;\n}\n',
  cpp: '#include <iostream>\n\nint main() {\n  std::cout << "Hello, world!" << std::endl;\n  return 0;\n}\n',
  cs: 'using System;\n\nclass Program {\n  static void Main() {\n    \n  }\n}\n',
  swift: 'import Foundation\n\n// Swift code\n',
  kt: 'fun main() {\n  println("Hello, world!")\n}\n',
  yaml: '# YAML\n',
  yml: '# YAML\n',
  xml: '<?xml version="1.0" encoding="UTF-8"?>\n<root>\n  \n</root>',
  sql: '-- SQL\n',
  sh: '#!/bin/bash\n\necho "Hello World"\n',
  bash: '#!/bin/bash\n\necho "Hello World"\n',
  dockerfile: 'FROM node:20-alpine\n\nWORKDIR /app\n\nCOPY package*.json ./\nRUN npm ci\n\nCOPY . .\n\nCMD ["node", "index.js"]\n',
  env: '# Environment variables\n',
  gitignore: 'node_modules/\ndist/\n.env\n*.log\n',
  toml: '# TOML\n',
  ini: '; INI configuration\n',
  cfg: '; Configuration\n',
  vue: '<template>\n  <div></div>\n</template>\n\n<script setup>\n\n</script>\n\n<style scoped>\n\n</style>\n',
  svelte: '<script>\n  let count = 0;\n</script>\n\n<h1>Hello Svelte!</h1>\n\n<style>\n  h1 { color: red; }\n</style>\n',
  tf: '# Terraform\n',
};

export function getTemplate(ext: string): string {
  const key = ext.toLowerCase().replace(/^\./, '');
  return FILE_TEMPLATES[key] || '';
}
